/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import java.util.Random;

public class App {

    public static void mostrar_lampada(Lampada lampada){
        if(lampada.verEstado())
            System.out.println("Lampada ligada");
        else
            System.out.println("Lampada desligada");
    }

    public static float numero(){
        Random random = new Random();
        float numero = random.nextFloat(11);
        return numero;
    }

    public static void main(String[] args) {
        //Exercicio 1 lampada
//        Lampada lampada1 = new Lampada();
//        Lampada lampada2 = new Lampada();
//
//        lampada1.ligar();
//        lampada2.desligar();
//
//        mostrar_lampada(lampada1);
//        mostrar_lampada(lampada2);
//
//        Lampada lampada3 = new Lampada();
//        System.out.printf("Lampadas criadas: %d\n", Lampada.getLampadasCriadas());

        //Exercicio 2 pessoa
//        Pessoa pessoa1 = new Pessoa("");
//        Pessoa pessoa2 = new Pessoa("Felipe", "191.234.001-41");
//        Pessoa pessoa3 = new Pessoa("Bruno", 25, "001.211.877-55");
//
//        if(pessoa1.setNome("Alice"))
//            System.out.println("nome criado");
//        else
//            System.out.println("nome invalido");
//        System.out.println(pessoa1.getNome());
//        System.out.println(pessoa2.getNome());
//        System.out.println(pessoa3.getNome());
//
//        System.out.println(pessoa1.getCpf());
//        System.out.println(pessoa2.getCpf());
//        System.out.println(pessoa3.getCpf());
//
//        if(pessoa1.setIdade(22))
//            System.out.println("Idade definida");
//        else
//            System.out.println("idade invalida");
//        System.out.println(pessoa1.getIdade());
//        System.out.println(pessoa2.getIdade());
//        System.out.println(pessoa3.getIdade());
//
//        pessoa2.felizAniversario();
//        System.out.println(pessoa2.getIdade());

        //Exercicio 3 Retangulo

//        Retangulo retangulo1 = new Retangulo(7, 8);
//        Retangulo retangulo2 = new Retangulo(2, 6);
//        Retangulo retangulo3 = new Retangulo(9, 3);
//
//        if(retangulo1.setAltura(4))
//            System.out.println("Altura deinifida");
//        else
//            System.out.println("Altura precisa ser positiva");
//
//        if(retangulo1.setLargura(5))
//            System.out.println("largura definida");
//        else
//            System.out.println("largura precisa ser positiva");
//
//        System.out.println(retangulo1.getArea());
//        System.out.println(retangulo1.getPerimetro());
//
//        System.out.println(Retangulo.maior_area.getArea());
//        System.out.println(Retangulo.menor_perimetro.getPerimetro());

        //Exercicio 4

//        Relogio relogio1 = new Relogio((byte)5);
//        Relogio relogio2 = new Relogio((byte)6, (byte)43);
//        Relogio relogio3 = new Relogio((byte)2, (byte)55, (byte)13);
//
//        relogio1.sincroniza(relogio2);
//
//        System.out.println(relogio1.getHora());
//        System.out.println(relogio2.getHora());
//        System.out.println(relogio3.getHora());
//
//        System.out.println(relogio3.diferenca(relogio2));

        //Exercicio 5

        Produto geladeira = new Produto("geladeira", 832);
        Produto microondas = new Produto("microondas", 499);
        Produto ferro = new Produto("ferro", 220);
        Produto fogao = new Produto("fogao", 750);
        Produto prato = new Produto("prato", 60);
        Produto frigobar = new Produto("frigobar", 560);

        frigobar.setDesconto(6);

        for(int i = 0; i < Produto.quantidade_produtos + 1; i++){
            System.out.println(Produto.tabela_produtos()[i]);
        }

        //Exercicio 6

//        Livro livro = new Livro();
//
//        livro.setTitulo("O Senhor dos Anéis - A Sociedade do Anel");
//        System.out.printf("Titulo: %s\n", livro.getTitulo());
//
//        livro.setAutor("J. R. R. Tolkien");
//        System.out.printf("Autor: %s\n", livro.getAutor());
//
//        livro.setTotal_paginas(464);
//        System.out.printf("total de paginas: %d\n", livro.getTotal_paginas());
//
//        livro.setCapitulo("Uma Festa Muito Esperada", 1);
//        livro.setCapitulo("A sombra do passado", 23);
//        livro.setCapitulo("Três é Demais", 44);
//        livro.setCapitulo("Um Atalho para Cogumelos", 66);
//        livro.setCapitulo("Uma Conspiração Desmascarada", 89);
//        livro.setCapitulo("A Floresta Velha", 110);
//        livro.setCapitulo("Em Casa de Tom Bombadil", 131);
//        livro.setCapitulo("Névoa nas Colinas dos Túmulos", 154);
//        livro.setCapitulo("No Pônei Empinado", 176);
//        livro.setCapitulo("Passolargo", 197);
//        livro.setCapitulo("Um Faca na Noite", 219);
//        livro.setCapitulo("Voo para o Vau", 240);
//        livro.setCapitulo("Muitos Encontros", 261);
//        livro.setCapitulo("O Conselho de Elrond", 282);
//        livro.setCapitulo("O Anel Vai para o Sul", 301);
//        livro.setCapitulo("Uma Jornada no Escuro", 320);
//        livro.setCapitulo("A Ponte de Khazad-dûm", 341);
//        livro.setCapitulo("Lothlórien", 361);
//        livro.setCapitulo("O Espelho de Galadriel", 383);
//        livro.setCapitulo("Adeus a Lórien", 403);
//        livro.setCapitulo("O Grande Rio", 423);
//        livro.setCapitulo("A Partida da Sociedade", 446);
//
//        livro.lerPaginas(90);
//
//        System.out.println(livro.getCapitulo());
//
//        livro.lerPaginas(300);
//
//        System.out.println(livro.getCapitulo());
//
//        livro.lerPaginas(100);
//
//        System.out.println(livro.getCapitulo());
//
//        livro.lerPaginas();
    }
}
