/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public class App {
    public static void main(String[] args) {
        Lampada lampada1 = new Lampada();
        Lampada lampada2 = new Lampada();

        lampada1.ligar();
        lampada2.desligar();

        System.out.println(lampada1);
        System.out.println(lampada2);
    }



}
